---
- name: Init network config
  shell: /export/servers/etcd/bin/etcdctl --ca-file=/export/servers/etcd/ssl/ca.pem --cert-file=/export/servers/etcd/ssl/server.pem --key-file=/export/servers/etcd/ssl/server-key.pem --endpoints="https://{{ groups['etcd'][0] }}:2379" set /coreos.com/network/config  '{ "Network":"10.10.0.0/17", "Backend":{"Type":"vxlan"}}'
  delegate_to: localhost

- name: Install flannel
  copy:
    src: "{{ item }}"
    dest: /export/servers/etcd/bin/{{ item }}
    mode: 755
  with_items:
    - flanneld
    - mk-docker-opts.sh

- name: Init flannel config
  template:
    dest: /export/servers/etcd/conf/flanneld
    src: flanneld.j2

- name: Init flannel service
  copy:
    dest: /usr/lib/systemd/system/flanneld.service
    src: flanneld.service

- name: Modify docker service step 1
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    insertbefore: ^ExecStart
    regexp: ^EnvironmentFile
    line: EnvironmentFile=/run/flannel/subnet.env

- name: Modify docker service step 2
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    regexp: ^ExecStart
    line: ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock $DOCKER_NETWORK_OPTIONS
