---
- name: Start flannld and enable service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: flannld

- name: Start docker and enable service
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: docker