---
#- name: install etcd
#  hosts: etcd
#  gather_facts: true
#  roles:
#  - etcd
#  tags:
#    - etcd

- name: init flannel network
  hosts: all
  gather_facts: true
  roles:
  - flanneld
  tags:
  - network

- name: init kubernetes controller
  hosts: all
  gather_facts: true
  roles:
  - kubernetes-controller
  tags:
  - controller

#- name: set local facts for kubernetes
#  hosts: kubernetes
#  gather_facts: true
#  vars_files:

#  roles:
#    - kubernetes
