---
- name: Create ETCD Directory
  file:
    dest: /export/servers/etcd/{{ item }}
    state: directory
  with_items:
    - bin
    - ssl
    - conf
    - data

- name: Create kubernetes Dirdctory
  file:
    dest: /export/servers/kubernetes/{{ item }}
    state: directory
  with_items:
    - bin
    - ssl
    - conf